<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>KifuwarabeGo2026.GameOasis.Gui</RootNamespace>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Docs\**" />
    <EmbeddedResource Remove="Docs\**" />
    <None Remove="Docs\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.FormalAdapter.Cgos\KifuwarabeGo2026.FormalAdapter.Cgos.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.FormalAdapter.Gtp\KifuwarabeGo2026.FormalAdapter.Gtp.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.FormalAdapter.Sgf\KifuwarabeGo2026.FormalAdapter.Sgf.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.StationeryUI\KifuwarabeGo2026.StationeryUI.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlaySpace.Go.GtpExtensions\KifuwarabeGo2026.Reference.PlaySpace.Go.GtpExtensions.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlaySpace.Go.Foundation\KifuwarabeGo2026.Reference.PlaySpace.Go.Foundation.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherEngine\KifuwarabeGo2026.LauncherEngine.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.GameOasis.Concierge\KifuwarabeGo2026.GameOasis.Concierge.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.GameOasis.Application\KifuwarabeGo2026.GameOasis.Application.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LobbyEngine\KifuwarabeGo2026.LobbyEngine.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LobbyEngine.JsonLines\KifuwarabeGo2026.LobbyEngine.JsonLines.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LobbyGui\KifuwarabeGo2026.LobbyGui.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayRoomGui.Common\KifuwarabeGo2026.Reference.PlayRoomGui.Common.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.Communication.Gtp\KifuwarabeGo2026.Reference.Communication.Gtp.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayRoomEngine.Go\KifuwarabeGo2026.Reference.PlayRoomEngine.Go.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayRoomEngine.Ponnuki\KifuwarabeGo2026.Reference.PlayRoomEngine.Ponnuki.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="default-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\Sessions\GameRecords\Current\" />
    <Folder Include="Application\Sessions\GameRecords\Review\" />
    <Folder Include="Application\Sessions\GameRecords\BeforeReview\" />
    <Folder Include="Application\Sessions\VariationSession\" />
    <Folder Include="Application\Sessions\GameRecords\Go\" />
    <Folder Include="Application\Sessions\GameRecords\" />
    <Folder Include="Presentation\BoardLens\RenSystem\" />
    <Folder Include="Presentation\BoardLens\LibertySystem\" />
    <Folder Include="Presentation\BoardLens\GlassesSystem\" />
    <Folder Include="Presentation\BoardLens\Shared\RenBoundaries\" />
    <Folder Include="Presentation\Pages\LocalMatch\Intermission\" />
    <Folder Include="Presentation\Pages\LocalMatch\Play\" />
    <Folder Include="Presentation\Pages\OnlineMatch\Cgos\SelectConnection\" />
    <Folder Include="Presentation\Pages\OnlineMatch\Cgos\Login\" />
    <Folder Include="Presentation\Pages\OnlineMatch\Cgos\Watch\" />
    <Folder Include="Presentation\Pages\EditTournamentRule\" />
    <Folder Include="Presentation\Pages\OnlineMatch\Cgos\" />
    <Folder Include="Presentation\Pages\PonnukiProviderSelection\" />
    <Folder Include="Presentation\Shared\SelectEntry\" />
    <Folder Include="Presentation\Shared\EditEntryProfile\" />
    <Folder Include="Presentation\Shared\EditEntryProfile\" />
    <Folder Include="Presentation\Shared\PopupFilePathTooltip\" />
    <Folder Include="Presentation\Shared\RightSidePanel\" />
    <Folder Include="Presentation\Shared\SeekButtonStrip\" />
    <Folder Include="Presentation\Shared\RandomSeedRow\" />
  </ItemGroup>
</Project>
