<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.GameOasis.Contracts\KifuwarabeGo2026.GameOasis.Contracts.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayDomain.Go\KifuwarabeGo2026.Reference.PlayDomain.Go.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayRoomGui.Common\KifuwarabeGo2026.Reference.PlayRoomGui.Common.csproj" />
  </ItemGroup>
</Project>
