<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>KifuwarabeGo2026.GameOasis.Gui.Presentation.StationeryUI</RootNamespace>
    <AssemblyName>KifuwarabeGo2026.StationeryUI</AssemblyName>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StationeryUI.MonoGame" Version="0.1.0" />
  </ItemGroup>
</Project>
