<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.GameOasis.Application\KifuwarabeGo2026.GameOasis.Application.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LobbyEngine\KifuwarabeGo2026.LobbyEngine.csproj" />
  </ItemGroup>
</Project>
