<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>EngineIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EngineIcon.ico" />
    <EmbeddedResource Include="EngineIcon.ico">
      <LogicalName>EngineIcon.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlaySpace.Go.Foundation\KifuwarabeGo2026.Reference.PlaySpace.Go.Foundation.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Reference.PlayerEngine\KifuwarabeGo2026.Reference.PlayerEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GoApps\Formal\OnlineMatch.Cgos\" />
  </ItemGroup>

</Project>
