<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KifuwarabeGo2026.LauncherEngine.JsonLines</AssemblyName>
    <RootNamespace>KifuwarabeGo2026.LauncherEngine.JsonLines</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherEngine\KifuwarabeGo2026.LauncherEngine.csproj" />
  </ItemGroup>
</Project>
