<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KifuwarabeGo2026.Launcher</AssemblyName>
    <RootNamespace>KifuwarabeGo2026.LauncherGui</RootNamespace>
    <RollForward>Major</RollForward>
    <ApplicationIcon>..\KifuwarabeGo2026.GameOasis.Gui\GuiIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\KifuwarabeGo2026.GameOasis.Gui\Content\Content.mgcb">
      <Link>Content\Content.mgcb</Link>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherEngine\KifuwarabeGo2026.LauncherEngine.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherEngine.Platform\KifuwarabeGo2026.LauncherEngine.Platform.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherGui.Platform\KifuwarabeGo2026.LauncherGui.Platform.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.LauncherGui.Presentation\KifuwarabeGo2026.LauncherGui.Presentation.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.StationeryUI\KifuwarabeGo2026.StationeryUI.csproj" />
  </ItemGroup>
</Project>
