<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <Version>3.7.0</Version>
    <AssemblyVersion>3.7.0.0</AssemblyVersion>
    <FileVersion>3.7.0.0</FileVersion>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.GtpExtensions\KifuwarabeGo2026.GtpExtensions.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Match\KifuwarabeGo2026.Match.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Shared\KifuwarabeGo2026.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="default-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Presentation\BoardLens\RenSystem\" />
    <Folder Include="Presentation\BoardLens\LibertySystem\" />
    <Folder Include="Presentation\BoardLens\GlassesSystem\" />
    <Folder Include="Presentation\BoardLens\Shared\" />
    <Folder Include="Presentation\Shared\PlayerSelector\" />
    <Folder Include="Presentation\Shared\TextBox\" />
    <Folder Include="Presentation\Shared\PopupNumberBox\" />
  </ItemGroup>
</Project>
