<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <Version>3.9.0</Version>
    <AssemblyVersion>3.9.0.0</AssemblyVersion>
    <FileVersion>3.9.0.0</FileVersion>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KifuwarabeGo2026.GtpExtensions\KifuwarabeGo2026.GtpExtensions.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Match\KifuwarabeGo2026.Match.csproj" />
    <ProjectReference Include="..\KifuwarabeGo2026.Shared\KifuwarabeGo2026.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="default-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\Sessions\GameRecords\Current\" />
    <Folder Include="Application\Sessions\GameRecords\Review\" />
    <Folder Include="Application\Sessions\GameRecords\BeforeReview\" />
    <Folder Include="Application\Sessions\VariationSession\" />
    <Folder Include="Application\Sessions\GameRecords\Go\" />
    <Folder Include="Application\Sessions\GameRecords\" />
    <Folder Include="Presentation\BoardLens\RenSystem\" />
    <Folder Include="Presentation\BoardLens\LibertySystem\" />
    <Folder Include="Presentation\BoardLens\GlassesSystem\" />
    <Folder Include="Presentation\BoardLens\Shared\" />
    <Folder Include="Presentation\Shared\PlayerSelector\" />
    <Folder Include="Presentation\Shared\EditEntryProfile\" />
    <Folder Include="Presentation\Shared\EditEntryProfile\" />
    <Folder Include="Presentation\StationeryUI\Controls\PopupNumberUnderline\" />
    <Folder Include="Presentation\StationeryUI\Controls\StickyNote\" />
    <Folder Include="Presentation\StationeryUI\Controls\TableRowLabel\" />
    <Folder Include="Presentation\StationeryUI\Controls\Button\" />
    <Folder Include="Presentation\StationeryUI\Controls\MultilineTextUnderline\" />
    <Folder Include="Presentation\StationeryUI\Controls\SinglelineTextUnderline\" />
    <Folder Include="Presentation\StationeryUI\Controls\Shared\Underline\" />
    <Folder Include="Presentation\StationeryUI\Controls\VerticalSectionLabel\" />
    <Folder Include="Presentation\StationeryUI\Controls\LinkUnderline\" />
  </ItemGroup>
</Project>
