<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KifuwarabeGo2026.Launcher.Core</AssemblyName>
    <RootNamespace>KifuwarabeGo2026.Launcher</RootNamespace>
    <Version>3.15.0</Version>
    <AssemblyVersion>3.15.0.0</AssemblyVersion>
    <FileVersion>3.15.0.0</FileVersion>
  </PropertyGroup>
</Project>
